chore: purge rewards and format
ubiquity/onboard.ubq.fi pull request #14
Opened 2024-03-13 00:50 UTC by Keyrxng

Relates to https://github.com/ubiquity/.github/issues/98
> ###### I guess it doesn't really but sort of

- purged `/rewards`
- brought over the used constants and abis
- `yarn format` fixes

2024-03-13 07:20 UTC, rndquu commented
@Keyrxng The build workflow is failing :(

2024-03-13 18:21 UTC, Keyrxng commented
`yarn knip` is passing but the workflow isn't I'm unsure how to approach that but the build should pass now that I've removed the lib causing the issue

2024-03-14 10:15 UTC, rndquu approved these changes

2024-03-14 22:02 UTC, pavlovcik requested changes
Code looks mostly fine just cspell related nits

2024-03-14 22:02 UTC, 0x4007 commented on .cspell.json
> +  "ignoreWords": ["wfzpewmlyiozupulbuur"]
Use an inline ignore directive in the file using it instead 

```
// cSpell: ignore wfzp...
```

2024-03-14 22:02 UTC, 0x4007 commented on .cspell.json
> +  "ignoreRegExpList": ["[0-9a-fA-F]{6}"],
This is for colors? Where is the issue?

2024-03-14 22:12 UTC, Keyrxng commented on .cspell.json
> +  "ignoreRegExpList": ["[0-9a-fA-F]{6}"],
It's just because I've added a comma it's registering a full line change but no dramas

2024-03-14 22:45 UTC, pavlovcik approved these changes

2024-03-18 16:41 UTC, gitcoindev commented
Hi @Keyrxng , the Knip configuration was fixed https://github.com/ubiquity/onboard.ubq.fi/pull/19 , most likely you will encounter merge conflicts in this area. After the merge conflicts are resolved I will also review and the pull request can be merged.

2024-03-20 09:43 UTC, Keyrxng commented
@gitcoindev ready when you are

2024-04-23 11:43 UTC, Keyrxng commented
Is this ready to be merged?

2024-04-23 13:36 UTC, gitcoindev commented
@Keyrxng thank you for pinging me again, yes!

2024-04-23 13:37 UTC, merged

2024-04-23 14:42 UTC, Keyrxng commented
> thank you for pinging me again

I can never tell if it's rude of me to be pinging or if that should be the default lmao I get you folks are busy but cheers

2024-04-23 18:54 UTC, gitcoindev commented
> > thank you for pinging me again
> 
> I can never tell if it's rude of me to be pinging or if that should be the default lmao I get you folks are busy but cheers

In my case: If I do not reply within 48hrs, do ping me -)